application: go-wxr-to-json-app
version: 1
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /convert
  script: _go_app

- url: /example.xml
  static_files: example.xml
  upload: example\.xml

- url: /.*
  static_files: index.html
  upload: index\.html
